### ISSUE TITLE
thread option not passed to kmc

### ISSUE THREAD

**Issue by andreas-wilm** [sanger-pathogens/iva#54]
Hi,

 I noticed that IVA's thread option (which is used for SMALT) is not passed down to KMC (__run_kmc() and _run_kmc_with_script()), even though it also supports multithreading via -t. No big problem, but an easy to implement improvement. 

Thanks for IVA
Andreas

**Comment by martinghunt** [comment]
Hi Andreas,

Thanks for pointing this out. I have vague recollections of having some issues with multithreading kmc on some servers when I was first developing IVA, which is why IVA might not be using it. I'll have a look into it again. As you say, it's easy enough to make the change to the code, I just might have to document some warnings about it.

Martin

**Comment by martinghunt** [comment]
Hi Andreas,

This is changed in the new version 1.0.3. By default kmc will now use the number of threads given by the --threads option. In case it causes issues, I added a new option --kmc_onethread to force kmc to use 1 thread regardless of the --threads option.

Martin

**Comment by andreas-wilm** [comment]
Great. Thanks
